#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

function findTodosInFile(filePath) {
  const content = fs.readFileSync(filePath, 'utf8');
  const regex = /<!--\s*TODO:(.*?)-->/gs;
  const todos = [];
  let m;
  while ((m = regex.exec(content)) !== null) {
    const raw = m[1].trim();
    const upToIndex = content.slice(0, m.index);
    const line = upToIndex.split('\n').length;
    todos.push({ file: filePath, line, raw });
  }
  return todos;
}

function walkDir(root, fn) {
  const entries = fs.readdirSync(root, { withFileTypes: true });
  for (const e of entries) {
    const full = path.join(root, e.name);
    if (e.isDirectory()) {
      if (['node_modules', '.git', 'dist', 'coverage'].includes(e.name)) continue;
      walkDir(full, fn);
    } else if (e.isFile()) {
      fn(full);
    }
  }
}

function main() {
  const results = [];
  const exts = ['.md', '.js'];
  walkDir(process.cwd(), (file) => {
    const rel = path.relative(process.cwd(), file);
    if (rel.startsWith('node_modules') || rel.startsWith('.git') || rel.startsWith('dist') || rel.startsWith('coverage')) return;
    if (!exts.includes(path.extname(file))) return;
    try {
      const todos = findTodosInFile(file);
      results.push(...todos);
    } catch (e) {
      // ignore read errors
    }
  });

  const outDir = path.join(process.cwd(), 'docs');
  if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, 'TODO_SUMMARY.md');
  const header = '# TODO Summary\n\nGenerated by `scripts/extract_todos.js`\n\n';
  if (results.length === 0) {
    fs.writeFileSync(outPath, header + 'No TODOs found.\n');
    console.log('No TODOs found.');
    return;
  }

  let md = header;
  md += '| File | Line | TODO |\n';
  md += '| --- | ---: | --- |\n';
  results.forEach((r) => {
    const rel = path.relative(process.cwd(), r.file).replace(/ /g, '%20');
    md += `| [${rel}](${rel}) | ${r.line} | ${r.raw.replace(/\|/g, '\\|')} |\n`;
  });

  fs.writeFileSync(outPath, md);
  console.log(`Wrote ${outPath} (${results.length} items)`);
}

main();
